events.listen("recipes", function (e) {
  e.remove({ id: "amb:bamboo_block" });
  e.remove({ id: "amb:charcoal_block" });
  e.remove({ id: "amb:charcoal_from_charcoal_block" });
  e.remove({ id: "amb:terracotta_slab_from_terracotta_stonecutting" });
  e.remove({ id: "amb:terracotta_slab" });
  e.remove({ id: "amb:terracotta_stairs_from_terracotta_stonecutting" });
  e.remove({ id: "amb:terracotta_stairs" });
  e.remove({ id: "amb:terracotta_wall_from_terracotta_stonecutting" });
  e.remove({ id: "amb:terracotta_wall" });
  e.remove({ id: "architects_palette:bone_meal" });
  e.remove({ id: "betterendforge:smithing_table_from_terminite_ingot" });
  e.remove({ id: "betterendforge:smithing_table_from_thallasium_ingot" });
  e.remove({ id: "betterendforge:terminite_ingot" });
  e.remove({ id: "bigreactors:reactor/basic/controller_ingots_uranium" });
  e.remove({ id: "bigreactors:reactor/basic/fuelrod_ingots_uranium" });
  e.remove({ id: "bigreactors:reactor/reinforced/controller_ingots_uranium" });
  e.remove({ id: "bigreactors:reactor/reinforced/fuelrod_ingots_uranium" });
  e.remove({ id: "bloodmagic:smelting/ingot_gold" });
  e.remove({ id: "bloodmagic:smelting/ingot_iron" });
  e.remove({ id: "botania:mana_infusion/mana_powder_dye" });
  e.remove({ id: "botania:red_string" });
  e.remove({ id: "byg:chain_boots" });
  e.remove({ id: "byg:chain_chestplate" });
  e.remove({ id: "byg:chain_helmet" });
  e.remove({ id: "byg:chain_leggings" });
  e.remove({ id: "byg:chain_plating" });
  e.remove({ id: "byg:compat/create/ametrine_ore" });
  e.remove({ id: "byg:compat/create/anthracite_ore" });
  e.remove({ id: "byg:compat/create/lignite_ore" });
  e.remove({ id: "chisel:charcoal/raw" });
  e.remove({ id: "create:blasting/ingot_lead_compat_immersiveengineering" });
  e.remove({ id: "create:blasting/ingot_lead_compat_mekanism" });
  e.remove({ id: "create:blasting/ingot_nickel_compat_immersiveengineering" });
  e.remove({ id: "create:blasting/ingot_silver_compat_immersiveengineering" });
  e.remove({ id: "create:blasting/ingot_tin_compat_mekanism" });
  e.remove({ id: "create:blasting/ingot_uranium_compat_immersiveengineering" });
  e.remove({ id: "create:blasting/silver_ingot_compat_iceandfire" });
  e.remove({ id: "create:crafting/materials/copper_ingot_from_compacting" });
  e.remove({ id: "create:crafting/materials/copper_ingot_from_decompacting" });
  e.remove({ id: "create:crafting/materials/copper_nugget_from_decompacting" });
  e.remove({ id: "create:smelting/dolomite" });
  e.remove({ id: "create:smelting/gabbro" });
  e.remove({ id: "create:smelting/ingot_lead_compat_immersiveengineering" });
  e.remove({ id: "create:smelting/ingot_lead_compat_mekanism" });
  e.remove({ id: "create:smelting/ingot_nickel_compat_immersiveengineering" });
  e.remove({ id: "create:smelting/ingot_silver_compat_immersiveengineering" });
  e.remove({ id: "create:smelting/ingot_tin_compat_mekanism" });
  e.remove({ id: "create:smelting/ingot_uranium_compat_immersiveengineering" });
  e.remove({ id: "create:smelting/silver_ingot_compat_iceandfire" });
  e.remove({ id: "createaddition:crafting/heater_exchange" });
  e.remove({ id: "ctiers:allthecompressed/centrifuge_casing_tier_creative" });
  e.remove({ id: "ctiers:allthecompressed/centrifuge_controller_tier_creative" });
  e.remove({ id: "ctiers:centrifuge_casing_tier_3_2" });
  e.remove({ id: "ctiers:centrifuge_casing_tier_4_2" });
  e.remove({ id: "ctiers:centrifuge_casing_tier_5_2" });
  e.remove({ id: "ctiers:centrifuge_controller_tier_3_2" });
  e.remove({ id: "ctiers:centrifuge_controller_tier_4_2" });
  e.remove({ id: "ctiers:centrifuge_controller_tier_5_2" });
  e.remove({ id: "ctiers:compressed_diamond_block" });
  e.remove({ id: "ctiers:compressed_emerald_block" });
  e.remove({ id: "ctiers:compressed_gold_block" });
  e.remove({ id: "ctiers:compressed_iron_block" });
  e.remove({ id: "ctiers:double_compressed_diamond_block" });
  e.remove({ id: "ctiers:double_compressed_emerald_block" });
  e.remove({ id: "ctiers:double_compressed_gold_block" });
  e.remove({ id: "ctiers:double_compressed_iron_block" });
  e.remove({ id: "ctiers:quadruple_compressed_diamond_block" });
  e.remove({ id: "ctiers:quadruple_compressed_emerald_block" });
  e.remove({ id: "ctiers:quadruple_compressed_gold_block" });
  e.remove({ id: "ctiers:quadruple_compressed_iron_block" });
  e.remove({ id: "ctiers:quintuple_compressed_diamond_block" });
  e.remove({ id: "ctiers:quintuple_compressed_emerald_block" });
  e.remove({ id: "ctiers:quintuple_compressed_gold_block" });
  e.remove({ id: "ctiers:quintuple_compressed_iron_block" });
  e.remove({ id: "ctiers:sextuple_compressed_diamond_block" });
  e.remove({ id: "ctiers:sextuple_compressed_emerald_block" });
  e.remove({ id: "ctiers:sextuple_compressed_gold_block" });
  e.remove({ id: "ctiers:sextuple_compressed_iron_block" });
  e.remove({ id: "ctiers:triple_compressed_diamond_block" });
  e.remove({ id: "ctiers:triple_compressed_emerald_block" });
  e.remove({ id: "ctiers:triple_compressed_gold_block" });
  e.remove({ id: "ctiers:triple_compressed_iron_block" });
  e.remove({ id: "cyclic:solidifier_honey_block0" });
  e.remove({ id: "draconicevolution:components/draconium_ingot" });
  e.remove({ id: "eidolon:decompress_lead_ingot" });
  e.remove({ id: "eidolon:smelt_stone_brick" });
  e.remove({ id: "extendedcrafting:ender_ingot" });
  e.remove({ id: "extrastorage:disk/shaped/disk_1024k" });
  e.remove({ id: "extrastorage:disk/shaped/disk_1048576k_fluid" });
  e.remove({ id: "extrastorage:disk/shaped/disk_16384k_fluid" });
  e.remove({ id: "extrastorage:disk/shaped/disk_16384k" });
  e.remove({ id: "extrastorage:disk/shaped/disk_256k" });
  e.remove({ id: "extrastorage:disk/shaped/disk_262144k_fluid" });
  e.remove({ id: "extrastorage:disk/shaped/disk_4096k" });
  e.remove({ id: "extrastorage:disk/shaped/disk_65536k_fluid" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_1024k" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_1048576k_fluid" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_16384k_fluid" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_16384k" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_256k" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_262144k_fluid" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_4096k" });
  e.remove({ id: "extrastorage:disk/shapeless/disk_65536k_fluid" });
  e.remove({ id: "extrastorage:part/storagepart_1024k" });
  e.remove({ id: "extrastorage:part/storagepart_1048576k_fluid" });
  e.remove({ id: "extrastorage:part/storagepart_16384k_fluid" });
  e.remove({ id: "extrastorage:part/storagepart_16384k" });
  e.remove({ id: "extrastorage:part/storagepart_256k" });
  e.remove({ id: "extrastorage:part/storagepart_262144k_fluid" });
  e.remove({ id: "extrastorage:part/storagepart_4096k" });
  e.remove({ id: "extrastorage:part/storagepart_65536k_fluid" });
  e.remove({ id: "extrastorage:storage_block/block_1024k" });
  e.remove({ id: "extrastorage:storage_block/block_1048576k_fluid" });
  e.remove({ id: "extrastorage:storage_block/block_16384k_fluid" });
  e.remove({ id: "extrastorage:storage_block/block_16384k" });
  e.remove({ id: "extrastorage:storage_block/block_256k" });
  e.remove({ id: "extrastorage:storage_block/block_262144k_fluid" });
  e.remove({ id: "extrastorage:storage_block/block_4096k" });
  e.remove({ id: "extrastorage:storage_block/block_65536k_fluid" });
  e.remove({ id: "iceandfire:copper_block_to_ingots" });
  e.remove({ id: "iceandfire:copper_ingot_to_nuggets" });
  e.remove({ id: "iceandfire:copper_ingot" });
  e.remove({ id: "iceandfire:furnace/copper_ingot_blasting" });
  e.remove({ id: "iceandfire:furnace/copper_ingot" });
  e.remove({ id: "iceandfire:furnace/silver_ingot_blasting" });
  e.remove({ id: "iceandfire:furnace/silver_ingot" });
  e.remove({ id: "iceandfire:silver_block_to_ingots" });
  e.remove({ id: "iceandfire:silver_ingot_to_nuggets" });
  e.remove({ id: "iceandfire:silver_ingot" });
  e.remove({ id: "iceandfire:wither_shard"});
  e.remove({ id: "immersiveengineering:crafting/component_iron" });
  e.remove({ id: "immersiveengineering:crafting/component_steel" });
  e.remove({ id: "immersiveengineering:crafting/constantan_mix" });
  e.remove({ id: "immersiveengineering:crafting/electrum_mix" });
  e.remove({ id: "immersiveengineering:crafting/gold_ingot_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/gold_ingot_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_aluminum" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_copper" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_gold" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_iron" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_lead" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_nickel" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_osmium" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_silver" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_tin" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_uranium" });
  e.remove({ id: "immersiveengineering:crafting/hammercrushing_zinc" });
  e.remove({ id: "immersiveengineering:crafting/ingot_aluminum_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_aluminum_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_aluminum_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_aluminum" });
  e.remove({ id: "immersiveengineering:crafting/ingot_constantan_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_constantan_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_constantan_to_nugget_constantan" });
  e.remove({ id: "immersiveengineering:crafting/ingot_constantan_to_storage_constantan" });
  e.remove({ id: "immersiveengineering:crafting/ingot_copper_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_copper_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_copper_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_copper_to_nugget_copper" });
  e.remove({ id: "immersiveengineering:crafting/ingot_copper_to_storage_copper" });
  e.remove({ id: "immersiveengineering:crafting/ingot_copper" });
  e.remove({ id: "immersiveengineering:crafting/ingot_electrum_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_electrum_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_electrum_to_electrum" });
  e.remove({ id: "immersiveengineering:crafting/ingot_electrum_to_nugget_electrum" });
  e.remove({ id: "immersiveengineering:crafting/ingot_electrum_to_storage_electrum" });
  e.remove({ id: "immersiveengineering:crafting/ingot_lead_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_lead_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_lead_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_lead_to_nugget_lead" });
  e.remove({ id: "immersiveengineering:crafting/ingot_lead_to_storage_lead" });
  e.remove({ id: "immersiveengineering:crafting/ingot_lead" });
  e.remove({ id: "immersiveengineering:crafting/ingot_nickel_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_nickel_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_nickel_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_nickel_to_nugget_nickel" });
  e.remove({ id: "immersiveengineering:crafting/ingot_nickel_to_storage_nickel" });
  e.remove({ id: "immersiveengineering:crafting/ingot_nickel" });
  e.remove({ id: "immersiveengineering:crafting/ingot_silver_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_silver_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_silver_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_silver_to_nugget_silver" });
  e.remove({ id: "immersiveengineering:crafting/ingot_silver_to_storage_silver" });
  e.remove({ id: "immersiveengineering:crafting/ingot_silver" });
  e.remove({ id: "immersiveengineering:crafting/ingot_steel_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_steel_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_steel_to_nugget_steel" });
  e.remove({ id: "immersiveengineering:crafting/ingot_steel_to_storage_steel" });
  e.remove({ id: "immersiveengineering:crafting/ingot_uranium_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_uranium_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/ingot_uranium_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/ingot_uranium_to_storage_uranium" });
  e.remove({ id: "immersiveengineering:crafting/ingot_uranium" });
  e.remove({ id: "immersiveengineering:crafting/iron_ingot_from_dust_from_blasting" });
  e.remove({ id: "immersiveengineering:crafting/iron_ingot_from_dust" });
  e.remove({ id: "immersiveengineering:crafting/nugget_constantan_to_ingot_constantan" });
  e.remove({ id: "immersiveengineering:crafting/nugget_constantan_to_ingot_constantan" });
  e.remove({ id: "immersiveengineering:crafting/nugget_copper_to_ingot_copper" });
  e.remove({ id: "immersiveengineering:crafting/nugget_electrum_to_ingot_electrum" });
  e.remove({ id: "immersiveengineering:crafting/nugget_lead_to_ingot_lead" });
  e.remove({ id: "immersiveengineering:crafting/nugget_nickel_to_ingot_nickel" });
  e.remove({ id: "immersiveengineering:crafting/nugget_silver_to_ingot_silver" });
  e.remove({ id: "immersiveengineering:crafting/nugget_steel_to_ingot_steel" });
  e.remove({ id: "immersiveengineering:crafting/nugget_uranium_to_ingot_uranium" });
  e.remove({ id: "immersiveengineering:crafting/storage_constantan_to_ingot_constantan" });
  e.remove({ id: "immersiveengineering:crafting/storage_copper_to_ingot_copper" });
  e.remove({ id: "immersiveengineering:crafting/storage_electrum_to_ingot_electrum" });
  e.remove({ id: "immersiveengineering:crafting/storage_lead_to_ingot_lead" });
  e.remove({ id: "immersiveengineering:crafting/storage_nickel_to_ingot_nickel" });
  e.remove({ id: "immersiveengineering:crafting/storage_silver_to_ingot_silver" });
  e.remove({ id: "immersiveengineering:crafting/storage_uranium_to_ingot_uranium" });
  e.remove({ id: "immersiveengineering:crusher/ingot_steel" });
  e.remove({ id: "immersiveengineering:metalpress/gear_gold" });
  e.remove({ id: "immersiveengineering:metalpress/gear_iron" });
  e.remove({ id: "immersiveengineering:squeezer/graphite_dust" });
  e.remove({ id: "immersivepetroleum:distillationtower/oilcracking" });
  e.remove({ id: "industrialforegoing:black_hole_controller" });
  e.remove({ id: "industrialforegoing:laser_drill_ore/tungsten" });
  e.remove({ id: "integrateddynamics:mechanical_squeezer/ore/dust_gold_nether" });
  e.remove({ id: "integrateddynamics:squeezer/ore/dust_gold_nether" });
  e.remove({ id: "ironchest:chests/copper_silver_chest" });
  e.remove({ id: "ironchest:chests/iron_gold_chest" });
  e.remove({ id: "ironchest:chests/silver_diamond_chest" });
  e.remove({ id: "ironchest:chests/vanilla_iron_chest" });
  e.remove({ id: "ironchest:upgrades/copper_to_iron_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/copper_to_silver_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/diamond_to_crystal_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/diamond_to_obsidian_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/gold_to_diamond_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/iron_to_gold_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/silver_to_gold_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/wood_to_copper_chest_upgrade" });
  e.remove({ id: "ironchest:upgrades/wood_to_iron_chest_upgrade" });
  e.remove({ id: "janoeo:blasting_aluminium_nether_ore_to_aluminium_ingot" });
  e.remove({ id: "janoeo:blasting_amethyst_ore_to_amethyst" });
  e.remove({ id: "janoeo:blasting_copper_nether_ore_to_copper_ingot" });
  e.remove({ id: "janoeo:blasting_copper_ore_to_copper_ingot" });
  e.remove({ id: "janoeo:blasting_gold_basalt_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:blasting_gold_dust_to_gold_ingot" });
  e.remove({ id: "janoeo:blasting_gold_end_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:blasting_gold_gravel_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:blasting_gold_nether_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:blasting_iron_basalt_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:blasting_iron_dust_to_iron_ingot" });
  e.remove({ id: "janoeo:blasting_iron_end_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:blasting_iron_gravel_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:blasting_iron_nether_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:blasting_lead_nether_ore_to_lead_ingot" });
  e.remove({ id: "janoeo:blasting_lead_ore_to_lead_ingot" });
  e.remove({ id: "janoeo:blasting_osmium_nether_ore_to_osmium_ingot" });
  e.remove({ id: "janoeo:blasting_osmium_ore_to_osmium_ingot" });
  e.remove({ id: "janoeo:blasting_silver_nether_ore_to_silver_ingot" });
  e.remove({ id: "janoeo:blasting_silver_ore_to_silver_ingot" });
  e.remove({ id: "janoeo:blasting_tin_nether_ore_to_tin_ingot" });
  e.remove({ id: "janoeo:blasting_tin_ore_to_tin_ingot" });
  e.remove({ id: "janoeo:blasting_uranium_nether_ore_to_uranium_ingot" });
  e.remove({ id: "janoeo:blasting_uranium_ore_to_uranium_ingot" });
  e.remove({ id: "janoeo:blasting_zinc_ore_to_zinc_ingot" });
  e.remove({ id: "janoeo:smelting_aluminium_nether_ore_to_aluminium_ingot" });
  e.remove({ id: "janoeo:smelting_amethyst_ore_to_amethyst" });
  e.remove({ id: "janoeo:smelting_copper_nether_ore_to_copper_ingot" });
  e.remove({ id: "janoeo:smelting_copper_ore_to_copper_ingot" });
  e.remove({ id: "janoeo:smelting_gold_basalt_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:smelting_gold_dust_to_gold_ingot" });
  e.remove({ id: "janoeo:smelting_gold_end_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:smelting_gold_gravel_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:smelting_gold_nether_ore_to_gold_ingot" });
  e.remove({ id: "janoeo:smelting_iron_basalt_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:smelting_iron_dust_to_iron_ingot" });
  e.remove({ id: "janoeo:smelting_iron_end_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:smelting_iron_gravel_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:smelting_iron_nether_ore_to_iron_ingot" });
  e.remove({ id: "janoeo:smelting_lead_nether_ore_to_lead_ingot" });
  e.remove({ id: "janoeo:smelting_lead_ore_to_lead_ingot" });
  e.remove({ id: "janoeo:smelting_osmium_nether_ore_to_osmium_ingot" });
  e.remove({ id: "janoeo:smelting_osmium_ore_to_osmium_ingot" });
  e.remove({ id: "janoeo:smelting_silver_nether_ore_to_silver_ingot" });
  e.remove({ id: "janoeo:smelting_silver_ore_to_silver_ingot" });
  e.remove({ id: "janoeo:smelting_tin_nether_ore_to_tin_ingot" });
  e.remove({ id: "janoeo:smelting_tin_ore_to_tin_ingot" });
  e.remove({ id: "janoeo:smelting_uranium_nether_ore_to_uranium_ingot" });
  e.remove({ id: "janoeo:smelting_uranium_ore_to_uranium_ingot" });
  e.remove({ id: "janoeo:smelting_zinc_ore_to_zinc_ingot" });
  e.remove({ id: "mapperbase:iron_rod" });
  e.remove({ id: "mapperbase:steel_axe" });
  e.remove({ id: "mapperbase:steel_block" });
  e.remove({ id: "mapperbase:steel_hoe" });
  e.remove({ id: "mapperbase:steel_ingot_from_blasting" });
  e.remove({ id: "mapperbase:steel_ingot_from_block" });
  e.remove({ id: "mapperbase:steel_ingot" });
  e.remove({ id: "mapperbase:steel_nugget_from_ingot" });
  e.remove({ id: "mapperbase:steel_pickaxe" });
  e.remove({ id: "mapperbase:steel_plate_from_blasting" });
  e.remove({ id: "mapperbase:steel_rod_from_blasting" });
  e.remove({ id: "mapperbase:steel_rod" });
  e.remove({ id: "mapperbase:steel_shovel" });
  e.remove({ id: "mapperbase:steel_slab" });
  e.remove({ id: "mapperbase:steel_sword" });
  e.remove({ id: "metalbarrels:barrels/iron_to_gold_barrel" });
  e.remove({ id: "metalbarrels:barrels/silver_to_diamond_barrel" });
  e.remove({ id: "metalbarrels:barrels/wood_to_gold_barrel" });
  e.remove({ id: "metalbarrels:barrels/wood_to_iron_barrel" });
  e.remove({ id: "morered:red_alloy_ingot_without_jumbo_furnace" });
  e.remove({ id: "mysticalagriculture:crops/chrome" });
  e.remove({ id: "mysticalagriculture:crops/iridium" });
  e.remove({ id: "mysticalagriculture:crops/mithril" });
  e.remove({ id: "mysticalagriculture:crops/titanium" });
  e.remove({ id: "mysticalagriculture:experience_capsule" });
  e.remove({ id: "mysticalagriculture:hostile_soulium_dagger" });
  e.remove({ id: "mysticalagriculture:passive_soulium_dagger" });
  e.remove({ id: "mysticalagriculture:seed/reprocessor/chrome" });
  e.remove({ id: "mysticalagriculture:seed/reprocessor/iridium" });
  e.remove({ id: "mysticalagriculture:seed/reprocessor/mithril" });
  e.remove({ id: "mysticalagriculture:seed/reprocessor/titanium" });
  e.remove({ id: "mysticalagriculture:soul_extractor" });
  e.remove({ id: "mysticalagriculture:soul_jar_empty" });
  e.remove({ id: "mysticalagriculture:soul_jar" });
  e.remove({ id: "mysticalagriculture:souls/arrow" });
  e.remove({ id: "mysticalagriculture:souls/beef" });
  e.remove({ id: "mysticalagriculture:souls/blaze_rod" });
  e.remove({ id: "mysticalagriculture:souls/bone" });
  e.remove({ id: "mysticalagriculture:souls/chicken" });
  e.remove({ id: "mysticalagriculture:souls/coal" });
  e.remove({ id: "mysticalagriculture:souls/cod" });
  e.remove({ id: "mysticalagriculture:souls/creeper_head" });
  e.remove({ id: "mysticalagriculture:souls/egg" });
  e.remove({ id: "mysticalagriculture:souls/ender_pearl" });
  e.remove({ id: "mysticalagriculture:souls/feather" });
  e.remove({ id: "mysticalagriculture:souls/ghast_tear" });
  e.remove({ id: "mysticalagriculture:souls/gunpowder" });
  e.remove({ id: "mysticalagriculture:souls/ink_sac" });
  e.remove({ id: "mysticalagriculture:souls/leather" });
  e.remove({ id: "mysticalagriculture:souls/mutton" });
  e.remove({ id: "mysticalagriculture:souls/porkchop" });
  e.remove({ id: "mysticalagriculture:souls/pufferfish" });
  e.remove({ id: "mysticalagriculture:souls/rabbit_foot" });
  e.remove({ id: "mysticalagriculture:souls/rabbit_hide" });
  e.remove({ id: "mysticalagriculture:souls/rabbit" });
  e.remove({ id: "mysticalagriculture:souls/rotten_flesh" });
  e.remove({ id: "mysticalagriculture:souls/salmon" });
  e.remove({ id: "mysticalagriculture:souls/scute" });
  e.remove({ id: "mysticalagriculture:souls/skeleton_skull" });
  e.remove({ id: "mysticalagriculture:souls/slime_ball" });
  e.remove({ id: "mysticalagriculture:souls/spider_eye" });
  e.remove({ id: "mysticalagriculture:souls/string" });
  e.remove({ id: "mysticalagriculture:souls/tropical_fish" });
  e.remove({ id: "mysticalagriculture:souls/wither_skeleton_skull" });
  e.remove({ id: "mysticalagriculture:souls/wool" });
  e.remove({ id: "mysticalagriculture:souls/zombie_head" });
  e.remove({ id: "overloaded:blocks/container/infinite_barrel" });
  e.remove({ id: "overloaded:blocks/container/infinite_capacitor" });
  e.remove({ id: "overloaded:blocks/container/infinite_tank" });
  e.remove({ id: "overloaded:blocks/container/true_infinite_barrel" });
  e.remove({ id: "overloaded:blocks/container/true_infinite_capacitor" });
  e.remove({ id: "overloaded:blocks/container/true_infinite_tank" });
  e.remove({ id: "overloaded:blocks/hyper_transfer/hyper_energy_receiver" });
  e.remove({ id: "overloaded:blocks/hyper_transfer/hyper_energy_sender" });
  e.remove({ id: "overloaded:blocks/hyper_transfer/hyper_fluid_receiver" });
  e.remove({ id: "overloaded:blocks/hyper_transfer/hyper_fluid_sender" });
  e.remove({ id: "overloaded:blocks/hyper_transfer/hyper_item_receiver" });
  e.remove({ id: "overloaded:blocks/hyper_transfer/hyper_item_sender" });
  e.remove({ id: "overloaded:blocks/nether_star_block" });
  e.remove({ id: "overloaded:blocks/nether_star_from_block" });
  e.remove({ id: "overloaded:items/crafting/fluid_core" });
  e.remove({ id: "overloaded:items/crafting/item_core" });
  e.remove({ id: "pamhc2crops:bread_grain" });
  e.remove({ id: "pamhc2foodcore:bread_dough" });
  e.remove({ id: "pamhc2foodcore:cookingoilitem_x2_nuts" });
  e.remove({ id: "pamhc2foodcore:cottoncandyitem" });
  e.remove({ id: "pamhc2foodcore:fruitpunchitem" });
  e.remove({ id: "pamhc2trees:bread_breadfruit" });
  // e.remove({ id: "projecte:collector_mk1" });
  // e.remove({ id: "projecte:collector_mk2" });
  // e.remove({ id: "projecte:collector_mk3" });
  // e.remove({ id: "projecte:condenser_mk1" });
  // e.remove({ id: "projecte:condenser_mk2" });
  // e.remove({ id: "projecte:philosophers_stone_alt" });
  // e.remove({ id: "projecte:relay_mk1" });
  // e.remove({ id: "projecte:relay_mk2" });
  // e.remove({ id: "projecte:relay_mk3" });
  // e.remove({ id: "projecte:repair_talisman_alt" });
  // e.remove({ id: "projecte:tome" });
  // e.remove({ id: "projectex:collector/mk1_alt" });
  // e.remove({ id: "projectex:collector/mk2_alt" });
  // e.remove({ id: "projectex:collector/mk3_alt" });
  // e.remove({ id: "projectex:compressed_refined_link" });
  // e.remove({ id: "projectex:personal_link" });
  // e.remove({ id: "projectex:refined_link" });
  // e.remove({ id: "projectex:relay/mk1_alt" });
  // e.remove({ id: "projectex:relay/mk2_alt" });
  // e.remove({ id: "projectex:relay/mk3_alt" });
  // e.remove({ id: "projectex:tome" });
  e.remove({ id: "quark:building/crafting/compressed/apple_crate" });
  e.remove({ id: "quark:building/crafting/compressed/bamboo_block" });
  e.remove({ id: "quark:building/crafting/compressed/beetroot_crate" });
  e.remove({ id: "quark:building/crafting/compressed/carrot_crate" });
  e.remove({ id: "quark:building/crafting/compressed/charcoal_block_uncompress" });
  e.remove({ id: "quark:building/crafting/compressed/charcoal_block" });
  e.remove({ id: "quark:building/crafting/compressed/potato_crate" });
  e.remove({ id: "quark:building/crafting/compressed/sugar_cane_block_uncompress" });
  e.remove({ id: "quark:building/crafting/compressed/sugar_cane_block" });
  e.remove({ id: "quark:building/crafting/rusty_iron_plate2" });
  e.remove({ id: "quark:crops/blue_blossom" });
  e.remove({ id: "quark:crops/lavender_blossom" });
  e.remove({ id: "quark:crops/orange_blossom" });
  e.remove({ id: "quark:crops/pink_blossom" });
  e.remove({ id: "quark:crops/yellow_blossom" });
  e.remove({ id: "quark:tweaks/crafting/utility/bent/bread" });
  e.remove({ id: "quark:tweaks/smelting/bone_meal_utility" });
  e.remove({ id: "rats:dragon_wing_vanilla" });
  e.remove({ id: "rats:rat_upgrade_dragon_vanilla" });
  e.remove({ id: "sophisticatedbackpacks:tank_upgrade" });
  e.remove({ id: "supplementaries:candelabra_recipe_3" });
  e.remove({ id: "supplementaries:candle_holder_recipe_3" });
  e.remove({ id: "tconstruct:common/materials/copper_ingot_blasting" });
  e.remove({ id: "tconstruct:common/materials/copper_ingot_from_block" });
  e.remove({ id: "tconstruct:common/materials/copper_ingot_from_nuggets" });
  e.remove({ id: "tconstruct:common/materials/copper_ingot_smelting" });
  e.remove({ id: "tconstruct:common/materials/copper_nugget_from_ingot" });
  e.remove({ id: "tconstruct:tools/modifiers/wither_bone_conversion" });
  // e.remove({ id: "thermal:bronze_dust_4" });
  // e.remove({ id: "thermal:constantan_dust_2" });
  // e.remove({ id: "thermal:electrum_dust_2" });
  // e.remove({ id: "thermal:enderium_dust_2" });
  e.remove({ id: "thermal:fire_charge/bronze_ingot_4" });
  e.remove({ id: "thermal:fire_charge/constantan_ingot_2" });
  e.remove({ id: "thermal:fire_charge/electrum_ingot_2" });
  e.remove({ id: "thermal:fire_charge/enderium_ingot_2" });
  e.remove({ id: "thermal:fire_charge/invar_ingot_3" });
  e.remove({ id: "thermal:fire_charge/lumium_ingot_4" });
  e.remove({ id: "thermal:fire_charge/signalum_ingot_4" });
  e.remove({ id: "thermal:furnace_1972435144" });
  // e.remove({ id: "thermal:invar_dust_3" });
  // e.remove({ id: "thermal:lumium_dust_4" });
  // e.remove({ id: "thermal:signalum_dust_4" });
  e.remove({ id: "thermal:smelting/copper_ingot_from_ore_blasting" });
  e.remove({ id: "thermal:smelting/copper_ingot_from_ore_smelting" });
  e.remove({ id: "thermal:smelting/gold_ingot_from_dust_blasting" });
  e.remove({ id: "thermal:smelting/gold_ingot_from_dust_smelting" });
  e.remove({ id: "thermal:smelting/iron_ingot_from_dust_blasting" });
  e.remove({ id: "thermal:smelting/iron_ingot_from_dust_smelting" });
  e.remove({ id: "thermal:soil/phytosoil_tilled" });
  e.remove({ id: "thermal:storage/bamboo_block" });
  e.remove({ id: "thermal:storage/gunpowder_block" });
  e.remove({ id: "undergarden:blast_undergarden_gold" });
  e.remove({ id: "undergarden:blast_undergarden_iron" });
  e.remove({ id: "undergarden:blast_utherium_ore" });
  e.remove({ id: "undergarden:smelt_undergarden_gold" });
  e.remove({ id: "undergarden:smelt_undergarden_iron" });
  e.remove({ id: "undergarden:smelt_utherium_ore" });
  // e.remove({ id: "xreliquary:uncrafting/packed_ice" });

  // var projecteEnergyGen = ['basic', 'dark', 'red', 'magenta', 'pink', 'purple', 'violet', 'blue', 'cyan', 'green', 'lime', 'yellow', 'orange', 'white', 'fading', 'final'];
  // projecteEnergyGen.forEach(name => {
  //   e.remove({ id: 'projectex:'+name+'_collector' });
  //   e.remove({ id: 'projectex:'+name+'_compressed_collector' });
  //   e.remove({ id: 'projectex:'+name+'_relay' });
  //   e.remove({ id: 'projectex:'+name+'_power_flower' });
  // });

  e.remove({ output: "immersiveengineering:ingot_steel" });
  e.remove({ output: "immersiveengineering:ingot_uranium" });
  e.remove({ output: "mapperbase:steel_boots" });
  e.remove({ output: "mapperbase:steel_chestplate" });
  e.remove({ output: "mapperbase:steel_helmet" });
  e.remove({ output: "mapperbase:steel_leggings" });
  e.remove({ output: "mapperbase:steel_nugget" });

  removeIO("mapperbase:flatter_hammer");
  removeIO("mapperbase:raw_steel");
  removeIO("metalbarrels:wood_to_copper");
  removeIO("metalbarrels:wood_to_iron");
  removeIO("metalbarrels:wood_to_silver");
  removeIO("metalbarrels:wood_to_gold");
  removeIO("metalbarrels:wood_to_diamond");
  removeIO("metalbarrels:wood_to_obsidian");
  removeIO("metalbarrels:wood_to_netherite");
  removeIO("metalbarrels:copper_to_iron");
  removeIO("metalbarrels:copper_to_silver");
  removeIO("metalbarrels:copper_to_gold");
  removeIO("metalbarrels:copper_to_diamond");
  removeIO("metalbarrels:copper_to_obsidian");
  removeIO("metalbarrels:iron_to_silver");
  removeIO("metalbarrels:iron_to_gold");
  removeIO("metalbarrels:iron_to_diamond");
  removeIO("metalbarrels:iron_to_obsidian");
  removeIO("metalbarrels:silver_to_gold");
  removeIO("metalbarrels:silver_to_diamond");
  removeIO("metalbarrels:silver_to_obsidian");
  removeIO("metalbarrels:gold_to_diamond");
  removeIO("metalbarrels:gold_to_obsidian");
  removeIO("metalbarrels:diamond_to_obsidian");
  removeIO("metalbarrels:wood_to_crystal");
  removeIO("metalbarrels:copper_to_crystal");
  removeIO("metalbarrels:iron_to_crystal");
  removeIO("metalbarrels:silver_to_crystal");
  removeIO("metalbarrels:gold_to_crystal");
  removeIO("metalbarrels:diamond_to_crystal");

  function removeIO(item) {
    e.remove({ output: item });
    e.remove({ input: item });
  }
});
