events.listen('item.registry', function (e) {
  e.create('antimatter_silicon').displayName('Tiny Antimatter Rubber').glow(true)
  e.create('brass_plate').displayName('Brass Plate')
  e.create('creative_plate').displayName('Creative Plate').glow(true)
  e.create('etherium_photovoltaic_cell').displayName('Etherium Photovoltaic Cell')
  e.create('gobber_photovoltaic_cell').displayName('Gobber Photovoltaic Cell')
  e.create('imperium_seed').displayName('§9Imperium Seed Base')
  e.create('inferium_seed').displayName('§eInferium Seed Base')
  e.create('insanium_seed').displayName('§5Insanium Seed Base')
  e.create('lapis_plate').displayName('Lapis Plate')
  e.create('machinarium_ingot').displayName('Machinarium Ingot')
  e.create('pile_of_quarkonium').displayName('Pile Of Quarkonium')
  e.create('platinum_ingot').displayName('Platinum Ingot')
  e.create('platinum_nugget').displayName('Platinum Nugget')
  e.create('prudentium_seed').displayName('§2Prudentium Seed Base')
  e.create('quarkonium_ingot').displayName('Quarkonium Ingot')
  e.create('quarkonium_nugget').displayName('Quarkonium Nugget')
  e.create('sphere').displayName('Sphere Of All Things')
  e.create('supremium_seed').displayName('§cSupremium Seed Base')
  e.create('tertium_seed').displayName('§6Tertium Seed Base')
  e.create('tungsten_ingot').displayName('Tungsten Ingot')
  e.create('tungsten_nugget').displayName('Tungsten Nugget')
  e.create('ultimate_essence').displayName('Ultimate Essence')
  e.create('ultimate_netherite').displayName('Ultimate Netherite Ingot')
  e.create('ultimate_netherite_lattice').displayName('Ultimate Netherite Lattice')
  e.create('ultimate_photovoltaic_cell').displayName('Ultimate Photovoltaic Cell')
  e.create('ultimate_seed').displayName('Ultimate Seed')
  e.create('zinc_plate').displayName('Zinc Plate')
})