#A priority list of Mod IDs that results of comb output should stem from, aka which mod you want the copper to come from.
preferredTagSource = ["minecraft", "chickens", "thermal", "tconstruct", "immersiveengineering", "create", "mekanism", "silents_mechanisms"]

#Odds of successful cross-breeding to ascend one tier
[Tiers]
	#Range: 0.0 ~ 1.0
	tier0 = 0.5
	#Range: 0.0 ~ 1.0
	tier1 = 1.0
	#Range: 0.0 ~ 1.0
	tier2 = 0.75
	#Range: 0.0 ~ 1.0
	tier3 = 0.5
	#Range: 0.0 ~ 1.0
	tier4 = 0.25
	#Range: 0.0 ~ 1.0
	tier5 = 0.125
	#Range: 0.0 ~ 1.0
	tier6 = 0.0625

#No comment
[BlockSpeed]
	#Prevent vanilla chickens from laying eggs. Of interest to modpack makers only. Default: false.
	disableEggLaying = false
	#The speed multiplier for the roost. Higher is faster. Default: 1.
	#Range: 0.0 ~ 100.0
	roostSpeed = 10.0
	#The speed multiplier for the breeder. Higher is faster. Default: 1.
	#Range: 0.01 ~ 100.0
	breederSpeed = 1.0
	#The time in ticks the breeder takes to create a new chicken
	#Range: > 20
	breedingTime = 600

#wild chicken spawn chance
[Baits]
	#The chance (per second) that a oak chicken bait will result in a spawn.
	#Range: 0.0020000000949949026 ~ 1.0
	oakChance = 0.009999999776482582
	#The chance (per second) that a sand chicken bait will result in a spawn.
	#Range: 0.0020000000949949026 ~ 1.0
	sandChance = 0.009999999776482582
	#The chance (per second) that a flint chicken bait will result in a spawn.
	#Range: 0.0020000000949949026 ~ 1.0
	flintChance = 0.009999999776482582
	#The chance (per second) that a quartz chicken bait will result in a spawn.
	#Range: 0.0020000000949949026 ~ 1.0
	quartzChance = 0.009999999776482582
	#The chance (per second) that a soulSand chicken bait will result in a spawn.
	#Range: 0.0020000000949949026 ~ 1.0
	soulSandChance = 0.009999999776482582

#World gen options
[World]
	#Chicken spawning weight (higher = more common)
	#Range: 0 ~ 100
	SpawnWeight = 10
	#Minimum number of Chickens to spawn at once
	#Range: 0 ~ 20
	SpawnMin = 2
	#Maximum number of Chickens to spawn at once
	#Range: 0 ~ 20
	SpawnMax = 5

#Options for Chicken breeding
[ChickenBreeding]
	#Chance for egg to spawn a Chicken (higher = rarer)
	#Range: 1 ~ 1000
	ChickenEggChance = 4
	#Chance for egg to spawn 4 Chicken instead of 1
	#Range: 1 ~ 1000
	ChickenEggMultiChance = 32
	#Delay in ticks between Chicken breeding
	#Range: 1 ~ 144000
	ChickenBreedingTime = 6000

